#!/bin/bash

# Generating ttf-files:

python mf2ttf.py underline

python mf2ttf.py latinr
python mf2ttf.py tengwarr
fontforge -script tengtelc.pe regular

python mf2ttf.py latinb
python mf2ttf.py tengwarb
fontforge -script tengtelc.pe bold

# Some cleaning up:

rm -f underline.21681gf
rm -f underline.log
rm -f underline.enc
rm -f underline.pe
rm -f underline.pk
rm -f underline.tfm
#rm -f underline.sfd

rm -f latinr.21681gf
rm -f latinr.log
rm -f latinr.enc
rm -f latinr.pe
rm -f latinr.pk
rm -f latinr.tfm
#rm -f latinr.sfd

rm -f tengwarr.21681gf
rm -f tengwarr.log
rm -f tengwarr.enc
rm -f tengwarr.pe
rm -f tengwarr.pk
rm -f tengwarr.tfm
#rm -f tengwarr.sfd

rm -f latinb.21681gf
rm -f latinb.log
rm -f latinb.enc
rm -f latinb.pe
rm -f latinb.pk
rm -f latinb.tfm
#rm -f latinb.sfd

rm -f tengwarb.21681gf
rm -f tengwarb.log
rm -f tengwarb.enc
rm -f tengwarb.pe
rm -f tengwarb.pk
rm -f tengwarb.tfm
#rm -f tengwarb.sfd

# Adding Graphite tables:

. ./addgr.bat

