#!/usr/bin/python

import sys
import os
import re

if len(sys.argv) != 2:
  print "This script converts the Substitutions in a OpenType Feature File into Graphite compiler format. Example:"
  print "  python " + sys.argv[0] + " mysubs.fea"
  print "This will generate a file mysubs.gdh, ready to be imported in your .gdl program."
  exit(1);

feafilename=sys.argv[1]
gdhfilename=os.path.splitext(feafilename)[0] + ".gdh"

feafile=open(feafilename,'rU')
gdhfile=open(gdhfilename,'w')
gdhfile.write("// This file is automatically generated by fea2gdh.py\n\n")
gdhfile.write("table(substitution)\n");
fealine=feafile.readline()
while fealine!='':
  raw=re.search("    sub \\\\([\w]*) \\\\([\w]*)  by \\\\([\w]*);",fealine)
  if raw!=None: gdhfile.write('  ps("'+raw.group(1)+'") ps("'+raw.group(2)+'") > ps("'+raw.group(3)+'"):(1 2) _ ;\n')
  raw=re.search("    sub \\\\([\w]*) \\\\([\w]*) \\\\([\w]*)  by \\\\([\w]*);",fealine)
  if raw!=None: gdhfile.write('  ps("'+raw.group(1)+'") ps("'+raw.group(2)+'") ps("'+raw.group(3)+'") > ps("'+raw.group(4)+'"):(1 2 3) _ _ ;\n')
  fealine=feafile.readline()
gdhfile.write("endtable;\n\n")
feafile.close()
gdhfile.close()

exit(0)

