#!/bin/bash

python3 mf2sfd.py underline

for WEIGHT in 100 200 300 400 500 600 700 800 900
do
	python3 mf2sfd.py latin $WEIGHT
	python3 mf2sfd.py tengwar $WEIGHT
	fontforge -script tengtelc.py $WEIGHT
done

rm -f underline.21681gf
rm -f underline.log
rm -f underline.enc
rm -f underline.pe
rm -f underline.pk
rm -f underline.tfm
rm -f underline.sfd
rm -f underline.gdh

rm -f latin.21681gf
rm -f latin.log
rm -f latin.enc
rm -f latin.pe
rm -f latin.pk
rm -f latin.tfm
rm -f latin.sfd
rm -f latin.gdh

rm -f tengwar.21681gf
rm -f tengwar.log
rm -f tengwar.enc
rm -f tengwar.pe
rm -f tengwar.pk
rm -f tengwar.tfm
rm -f tengwar.sfd
rm -f tengwar.gdh

rm -f tengtelc.ttf
