import csv
csvreader=csv.reader(open("tehtarshift.csv", "rb"))
gdf=open('tehtarshift.gdh','w')
gdf.write("// NOTE: This file is automatically generated. Do not edit!\r\n\r\n")
for row in zip(*csvreader):
   colnum=1
   for cell in row:
      if colnum==1:
         gdf.write(cell.ljust(16)+"= (")
      elif colnum==len(row):
         gdf.write(cell.rjust(20)+" );\r\n")
      else:
         gdf.write(cell.rjust(20)+",")
      colnum=colnum+1
gdf.write("\r\n")
gdf.close()

