import csv

txf=open('tehtarshift.tex','w')
txf.write("%&program=xelatex\n")
txf.write("% NOTE: This file is automatically generated. Do not edit!\n\n")
txf.write("\documentclass{article}\n")
txf.write("\usepackage{fontspec}\n")
txf.write("\pagestyle{empty}\n")
txf.write("\\font\\tengtelc=\"[./tengtelc_nogr.ttf]\" at 40pt\n")
txf.write("\\begin{document}\n")
txf.write("\\tengtelc\n")

csvreader=csv.reader(open("tehtarshift.csv", "rb"))
gdf=open('tehtarshift.gdh','w')
gdf.write("// NOTE: This file is automatically generated. Do not edit!\r\n\r\n")
uniquechars=set()
basechars=[]
colnum=0
for col in zip(*csvreader):
   rownum=0
   for cell in col:
      if rownum==0:
         gdf.write(cell.replace('.', '_').ljust(16)+"= (")
         if cell=="Underliners":
            underliners=True
         else:
            underliners=False
      else:
         uniquechars.add(cell)
         gdf.write(cell.replace('.', '_').rjust(20))
         if rownum==len(col)-1:
            gdf.write(" );\r\n")
         else:
            gdf.write(",")
         if colnum==0:
            basechars.append(cell)
         else:
            if underliners:
               txf.write("\\rule[-20pt]{0pt}{60pt}\\XeTeXglyph\\XeTeXglyphindex\""+cell+"\" \\XeTeXglyph\\XeTeXglyphindex\""+basechars[rownum-1]+"\" { }\n") 
            else:
               txf.write("\\rule[-20pt]{0pt}{60pt}\\XeTeXglyph\\XeTeXglyphindex\""+basechars[rownum-1]+"\" \\XeTeXglyph\\XeTeXglyphindex\""+cell+"\" { }\n") 
      rownum=rownum+1
   colnum=colnum+1
   txf.write("\n") 
gdf.write("\r\n")
gdf.close()
txf.write("\\end{document}\n\n")
txf.close()

mff=open('tehtarshift.mf','w')
mff.write("% NOTE: This file is automatically generated. Do not edit!\n\n")
for char in sorted(uniquechars):
   dotloc=char.find(".")
   if dotloc!=-1:
      base=char[:dotloc]
      longvar=char[dotloc:]
      xshift="0"
      yshift="0"
      if char[-4:-2].isdigit() and char[-1].isdigit():
         var=char[dotloc:-4]
         xshift=char[-4:-2]
         if char[-2]=="u":
            yshift=char[-1]
         elif char[-2]=="d":
            yshift="-"+char[-1]
      elif char[-2:].isdigit():
         var=char[dotloc:-2]
         xshift=char[-2:]
      #print char + " : " + base + " : " + longvar + " : " + var + " : " + xshift + " : " + yshift
      if xshift!="0" or yshift!="0":
         mff.write("shiftedref("+base+"&\""+var+"\","+base+"&\""+longvar+"\",(-0.125pt*"+xshift+",0.25pt*"+yshift+"));\n")
mff.write("message\"\";\n\n")
mff.close()



